# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers configuration
[[headers]]
  # Define headers for all paths
  for = "/*"
    [headers.values]
    # Example headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Optional: Custom redirects or headers for specific paths
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[headers]]
  for = "/some-path"
    [headers.values]
    Cache-Control = "public, max-age=3600"
